version: '3.7'

services:
  db:
    image: postgres:14
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./api/db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: './api'
    container_name: api
    restart: always
    volumes:
      - ./api:/home/node/app
    ports:
      - '3333:3333'
    depends_on:
      - db

  app:
    container_name: app
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - '8080:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
      - '16543:80'
    depends_on:
      - db
